# Generated by Django 5.1.15 on 2026-02-25 20:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(default="COP", max_length=8)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=19, max_digits=5),
                ),
                ("invoice_prefix", models.CharField(default="FAC", max_length=10)),
                ("next_invoice_number", models.IntegerField(default=1)),
                ("low_stock_default", models.IntegerField(default=3)),
                ("sizes", models.JSONField(blank=True, default=list)),
                ("colors", models.JSONField(blank=True, default=list)),
                ("categories_custom", models.JSONField(blank=True, default=list)),
                (
                    "billing_legal_name",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "billing_tax_id",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "billing_address",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "billing_postal_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "billing_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "billing_phone",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "billing_city",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "billing_country",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "billing_vat_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
            ],
        ),
    ]
