# Generated by Django 5.1.15 on 2026-02-26 00:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.BigIntegerField(db_index=True, unique=True)),
                ('currency', models.CharField(default='COP', max_length=8)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('invoice_prefix', models.CharField(default='FAC', max_length=10)),
                ('next_invoice_number', models.IntegerField(default=1)),
                ('low_stock_default', models.IntegerField(default=3)),
                ('sizes', models.JSONField(blank=True, default=list)),
                ('colors', models.JSONField(blank=True, default=list)),
                ('categories_custom', models.JSONField(blank=True, default=list)),
                ('billing_legal_name', models.CharField(blank=True, default='', max_length=160)),
                ('billing_tax_id', models.CharField(blank=True, default='', max_length=40)),
                ('billing_address', models.CharField(blank=True, default='', max_length=200)),
                ('billing_postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('billing_email', models.EmailField(blank=True, default='', max_length=254)),
                ('billing_phone', models.CharField(blank=True, default='', max_length=32)),
                ('billing_city', models.CharField(blank=True, default='', max_length=80)),
                ('billing_country', models.CharField(blank=True, default='', max_length=80)),
                ('billing_vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.BigIntegerField(db_index=True, unique=True)),
                ('smtp_host', models.CharField(blank=True, default='', max_length=160)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, default='', max_length=160)),
                ('smtp_password_ciphertext', models.TextField(blank=True, default='')),
                ('smtp_password_nonce', models.CharField(blank=True, default='', max_length=64)),
                ('smtp_password_kid', models.CharField(blank=True, default='', max_length=32)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
