# Generated by Django 5.1.15 on 2026-02-25 22:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0002_fix_billing_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="storesettings",
            name="base_currency",
            field=models.CharField(
                choices=[("COP", "COP"), ("USD", "USD")], default="COP", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="fx_usd_cop_rate",
            field=models.DecimalField(
                decimal_places=6, default=Decimal("0"), max_digits=18
            ),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="rounding_policy",
            field=models.CharField(
                choices=[("BANKERS", "Bankers"), ("HALF_UP", "Half up")],
                default="HALF_UP",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="show_dual_currency",
            field=models.BooleanField(default=True),
        ),
    ]
