# Generated by Django 5.1.15 on 2026-02-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_fix_stock_cost_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="variant",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
