# Generated by Django 5.1.15 on 2026-02-25

import apps.common.storage_backends
import apps.inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_variant_cost_variant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=apps.common.storage_backends.PublicMediaStorage(), upload_to=apps.inventory.models.product_image_upload_to),
        ),
    ]
