# Generated by Django 5.1.15 on 2026-02-27 01:43

import apps.common.storage
import apps.inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=apps.common.storage.get_media_storage,
                upload_to=apps.inventory.models.variant_image_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=apps.common.storage.get_media_storage,
                upload_to=apps.inventory.models.product_image_upload_to,
            ),
        ),
    ]
