# Generated by Django 5.1.15 on 2026-02-27 14:18

from django.db import migrations, models


def backfill_default_sale_price(apps, schema_editor):
    Variant = apps.get_model('inventory', 'Variant')
    Variant.objects.filter(default_sale_price=0).update(default_sale_price=models.F('price'))


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_variant_image_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="default_sale_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RunPython(backfill_default_sale_price, migrations.RunPython.noop),
    ]
