# Generated by Django 5.1.15 on 2026-02-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_productstock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="suggested_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
